name: Go
on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v3
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: make test
